# Generated by Django 5.2.5 on 2025-08-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry-Level'), ('MID', 'Mid-Level'), ('SENIOR', 'Senior')], max_length=20)),
                ('description', models.TextField()),
                ('application_link', models.URLField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
